[platformio]
# Forces PlatformIO to look inside the correct subfolder for the main sketch
src_dir = DeautherX

[env:deauther_watch_x]
platform = espressif8266@2.6.3
board = d1_mini
framework = arduino
monitor_speed = 115200

# Fixes compiler errors related to strict modern C++ type definitions
build_flags = 
    -fpermissive
    -Wno-comment
    -D ESP8266

# Automatically pulls the exact legacy libraries needed for the display and web server
lib_deps =
    Adafruit NeoPixel
    ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays
    bblanchon/ArduinoJson @ 5.13.4
